import type { User, Post, Listing, Video, Group, LiveStream, GamePost, LikedPage } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "John Smith",
    email: "john@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/32.jpg",
    coverImg: "/serene-mountain-lake.png",
    bio: "Software developer | Tech enthusiast | Coffee lover ☕",
    location: "San Francisco, CA",
    friends: ["user-2", "user-3", "user-4", "user-5"],
    online: true,
  },
  {
    id: "user-2",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    profileImg: "https://randomuser.me/api/portraits/women/44.jpg",
    coverImg: "/beach-sunset.png",
    bio: "Designer | Artist | Traveler ✈️",
    location: "New York, NY",
    friends: ["user-1", "user-3"],
    online: true,
  },
  {
    id: "user-3",
    name: "Michael Chen",
    email: "michael@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "Product Manager | Startup enthusiast 🚀",
    location: "Seattle, WA",
    friends: ["user-1", "user-2", "user-4"],
    online: false,
  },
  {
    id: "user-4",
    name: "Emily Rodriguez",
    email: "emily@example.com",
    profileImg: "https://randomuser.me/api/portraits/women/33.jpg",
    bio: "Photographer | Nature lover 🌿",
    location: "Austin, TX",
    friends: ["user-1", "user-3", "user-5"],
    online: true,
  },
  {
    id: "user-5",
    name: "David Kim",
    email: "david@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/45.jpg",
    bio: "Marketing specialist | Foodie 🍕",
    location: "Los Angeles, CA",
    friends: ["user-1", "user-4"],
    online: false,
  },
  {
    id: "user-6",
    name: "Jessica Lee",
    email: "jessica@example.com",
    profileImg: "https://randomuser.me/api/portraits/women/28.jpg",
    location: "Boston, MA",
    friends: ["user-1"],
    online: true,
  },
  {
    id: "user-7",
    name: "James Wilson",
    email: "james@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/12.jpg",
    location: "Chicago, IL",
    friends: ["user-1"],
    online: true,
  },
  {
    id: "user-8",
    name: "Maria Garcia",
    email: "maria@example.com",
    profileImg: "https://randomuser.me/api/portraits/women/19.jpg",
    location: "Miami, FL",
    friends: ["user-1"],
    online: false,
  },
  {
    id: "user-9",
    name: "Hamza Ahmed",
    email: "hamza@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/55.jpg",
    coverImg: "/city-skyline-night.png",
    bio: "Full-stack developer | Gaming enthusiast 🎮",
    location: "Karachi, Pakistan",
    friends: ["user-1", "user-10", "user-11"],
    online: true,
  },
  {
    id: "user-10",
    name: "Zulkifal Khan",
    email: "zulki@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/67.jpg",
    coverImg: "/mountain-peak-sunrise.jpg",
    bio: "Digital marketer | Content creator | Entrepreneur 💼",
    location: "Lahore, Pakistan",
    friends: ["user-1", "user-9", "user-11"],
    online: true,
  },
  {
    id: "user-11",
    name: "Kushnood Ali",
    email: "kushnood@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/78.jpg",
    bio: "UI/UX Designer | Creative thinker | Coffee addict ☕",
    location: "Islamabad, Pakistan",
    friends: ["user-1", "user-9", "user-10"],
    online: false,
  },
  {
    id: "user-12",
    name: "Hamza Malik",
    email: "hamzam@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/83.jpg",
    bio: "Data scientist | AI researcher 🤖",
    location: "Dubai, UAE",
    friends: ["user-1"],
    online: true,
  },
  {
    id: "user-13",
    name: "Zulki Abbas",
    email: "zulkia@example.com",
    profileImg: "https://randomuser.me/api/portraits/men/91.jpg",
    bio: "Frontend developer | React enthusiast ⚛️",
    location: "London, UK",
    friends: ["user-1", "user-9"],
    online: false,
  },
]

export const mockPosts: Post[] = [
  {
    id: "post-1",
    userId: "user-2",
    caption: "Just finished an amazing project! Excited to share it with you all soon. 🎨✨",
    image: "/creative-design-workspace.jpg",
    likes: ["user-1", "user-3", "user-4"],
    comments: [
      {
        id: "comment-1",
        userId: "user-1",
        text: "Looks amazing! Can't wait to see the final result!",
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
      {
        id: "comment-2",
        userId: "user-3",
        text: "This is incredible work! 🔥",
        createdAt: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
    shares: 5,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "post-2",
    userId: "user-3",
    caption: "Beautiful day at the park! Sometimes you just need to disconnect and enjoy nature. 🌳☀️",
    image: "/park-nature-trees.jpg",
    likes: ["user-1", "user-2", "user-4", "user-5"],
    comments: [],
    shares: 2,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "post-3",
    userId: "user-4",
    caption: "Captured this stunning sunset yesterday! Mother nature never disappoints. 📸🌅",
    image: "/golden-hour-sunset-sky.jpg",
    likes: ["user-1", "user-2", "user-3", "user-5", "user-6"],
    comments: [
      {
        id: "comment-3",
        userId: "user-1",
        text: "Wow! The colors are incredible!",
        createdAt: new Date(Date.now() - 9000000).toISOString(),
      },
    ],
    shares: 8,
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: "post-4",
    userId: "user-5",
    caption: "Just tried this new restaurant downtown and it was absolutely delicious! Highly recommend the pasta. 🍝❤️",
    likes: ["user-1", "user-4"],
    comments: [
      {
        id: "comment-4",
        userId: "user-4",
        text: "I need to check this place out!",
        createdAt: new Date(Date.now() - 5400000).toISOString(),
      },
      {
        id: "comment-5",
        userId: "user-1",
        text: "Let's go together next week!",
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
    ],
    shares: 3,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: "post-5",
    userId: "user-1",
    caption:
      "Excited to announce that I'm starting a new position next month! Thanks to everyone who supported me on this journey. 🎉💼",
    likes: ["user-2", "user-3", "user-4", "user-5", "user-6", "user-7"],
    comments: [
      {
        id: "comment-6",
        userId: "user-2",
        text: "Congratulations! You deserve it! 🎊",
        createdAt: new Date(Date.now() - 10800000).toISOString(),
      },
      {
        id: "comment-7",
        userId: "user-3",
        text: "That's awesome news! Well done!",
        createdAt: new Date(Date.now() - 9000000).toISOString(),
      },
      {
        id: "comment-8",
        userId: "user-4",
        text: "So happy for you! 🥳",
        createdAt: new Date(Date.now() - 7200000).toISOString(),
      },
    ],
    shares: 12,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
]

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    userId: "user-9",
    title: "iPhone 14 Pro Max - 256GB",
    description:
      "Barely used iPhone 14 Pro Max in excellent condition. Deep Purple color. Comes with original box, charger, and case. No scratches or damage. Battery health at 98%.",
    price: 899,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "like_new",
    location: "Karachi, Pakistan",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    likes: ["user-1", "user-10"],
    saved: ["user-1", "user-2"],
  },
  {
    id: "listing-2",
    userId: "user-10",
    title: "Gaming Laptop - ROG Strix G15",
    description:
      "High-performance gaming laptop with RTX 3070, Ryzen 9 processor, 32GB RAM, 1TB SSD. Perfect for gaming and content creation. Barely 6 months old with warranty remaining.",
    price: 1499,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "like_new",
    location: "Lahore, Pakistan",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    likes: ["user-1", "user-9", "user-11"],
    saved: ["user-1"],
  },
  {
    id: "listing-3",
    userId: "user-2",
    title: "Vintage Leather Sofa",
    description:
      "Beautiful vintage brown leather sofa in great condition. 3-seater, very comfortable. Moving to a smaller apartment so need to sell. Pickup only.",
    price: 450,
    image: "/placeholder.svg?height=400&width=400",
    category: "Furniture",
    condition: "used",
    location: "New York, NY",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    likes: ["user-3", "user-4"],
    saved: ["user-3"],
  },
  {
    id: "listing-4",
    userId: "user-11",
    title: "Canon EOS R6 Camera Body",
    description:
      "Professional mirrorless camera in mint condition. Only 5000 shutter count. Comes with 2 batteries, charger, and original packaging. Perfect for photography enthusiasts.",
    price: 1899,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "like_new",
    location: "Islamabad, Pakistan",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    likes: ["user-1", "user-4", "user-9"],
    saved: ["user-1", "user-4"],
  },
  {
    id: "listing-5",
    userId: "user-4",
    title: "Mountain Bike - Trek X-Caliber",
    description:
      "Excellent condition mountain bike, barely used. 29-inch wheels, 21-speed gear system. Recently serviced. Great for trails and city riding.",
    price: 399,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports",
    condition: "like_new",
    location: "Austin, TX",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    likes: ["user-1", "user-5"],
    saved: ["user-5"],
  },
  {
    id: "listing-6",
    userId: "user-3",
    title: "MacBook Pro 16-inch M2 Pro",
    description:
      "Brand new MacBook Pro with M2 Pro chip, 16GB RAM, 512GB SSD. Space Gray. Still under warranty. Selling because I got a new one from work.",
    price: 2199,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "new",
    location: "Seattle, WA",
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    likes: ["user-1", "user-2", "user-9", "user-10"],
    saved: ["user-1", "user-9"],
  },
  {
    id: "listing-7",
    userId: "user-5",
    title: "Designer Watch - Omega Seamaster",
    description:
      "Authentic Omega Seamaster with box and papers. Excellent condition, serviced last year. Classic blue dial. A timeless piece for any collection.",
    price: 3499,
    image: "/placeholder.svg?height=400&width=400",
    category: "Fashion",
    condition: "used",
    location: "Los Angeles, CA",
    createdAt: new Date(Date.now() - 604800000).toISOString(),
    likes: ["user-1", "user-3"],
    saved: ["user-1"],
  },
  {
    id: "listing-8",
    userId: "user-1",
    title: "Dining Table Set - 6 Chairs",
    description:
      "Modern wooden dining table with 6 matching chairs. Great condition, minor wear on seats. Perfect for family dinners. Dimensions: 180cm x 90cm.",
    price: 350,
    image: "/placeholder.svg?height=400&width=400",
    category: "Furniture",
    condition: "used",
    location: "San Francisco, CA",
    createdAt: new Date(Date.now() - 691200000).toISOString(),
    likes: ["user-2", "user-3"],
    saved: ["user-2"],
  },
  {
    id: "listing-9",
    userId: "user-12",
    title: "PlayStation 5 with 2 Controllers",
    description:
      "PS5 console with disc drive, 2 DualSense controllers, and 5 games included. Excellent condition, barely used. All cables and original box included.",
    price: 549,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "like_new",
    location: "Dubai, UAE",
    createdAt: new Date(Date.now() - 777600000).toISOString(),
    likes: ["user-9", "user-10", "user-11"],
    saved: ["user-9", "user-1"],
  },
  {
    id: "listing-10",
    userId: "user-6",
    title: "Yoga Mat & Accessories Set",
    description:
      "Premium yoga mat with carrying bag, 2 blocks, and resistance bands. Lightly used, very clean. Perfect for home workouts or yoga classes.",
    price: 45,
    image: "/placeholder.svg?height=400&width=400",
    category: "Sports",
    condition: "like_new",
    location: "Boston, MA",
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    likes: ["user-4"],
    saved: [],
  },
  {
    id: "listing-11",
    userId: "user-13",
    title: "Samsung 55-inch 4K Smart TV",
    description:
      "Crystal clear 4K display, HDR support, smart features. Less than 1 year old. Moving overseas, must sell quickly. Includes wall mount and remote.",
    price: 499,
    image: "/placeholder.svg?height=400&width=400",
    category: "Electronics",
    condition: "like_new",
    location: "London, UK",
    createdAt: new Date(Date.now() - 950400000).toISOString(),
    likes: ["user-1", "user-9"],
    saved: ["user-1"],
  },
  {
    id: "listing-12",
    userId: "user-7",
    title: "Electric Guitar - Fender Stratocaster",
    description:
      "Classic Fender Stratocaster in sunburst finish. Comes with amp, cable, and guitar case. Great for beginners and intermediate players.",
    price: 799,
    image: "/placeholder.svg?height=400&width=400",
    category: "Music",
    condition: "used",
    location: "Chicago, IL",
    createdAt: new Date(Date.now() - 1036800000).toISOString(),
    likes: ["user-5"],
    saved: [],
  },
]

export const mockVideos: Video[] = [
  {
    id: "video-1",
    userId: "user-9",
    title: "Amazing Gaming Highlights - Call of Duty MW3",
    thumbnail: "/gaming-highlights.png",
    views: 15420,
    duration: "12:35",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    likes: ["user-1", "user-10", "user-11"],
    category: "Gaming",
  },
  {
    id: "video-2",
    userId: "user-10",
    title: "How to Build a Stunning Website in 2024",
    thumbnail: "/web-development-tutorial.png",
    views: 28350,
    duration: "18:42",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    likes: ["user-1", "user-9", "user-11", "user-13"],
    category: "Education",
  },
  {
    id: "video-3",
    userId: "user-2",
    title: "Creative Design Process - Behind the Scenes",
    thumbnail: "/design-process-creative.jpg",
    views: 9840,
    duration: "15:20",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    likes: ["user-1", "user-3", "user-4"],
    category: "Art & Design",
  },
  {
    id: "video-4",
    userId: "user-4",
    title: "Nature Photography Tips for Beginners",
    thumbnail: "/nature-photography-landscape.jpg",
    views: 12560,
    duration: "10:15",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    likes: ["user-1", "user-2", "user-5"],
    category: "Photography",
  },
  {
    id: "video-5",
    userId: "user-11",
    title: "UI/UX Design Trends 2024",
    thumbnail: "/ui-ux-design-modern.jpg",
    views: 21870,
    duration: "14:28",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    likes: ["user-1", "user-9", "user-10", "user-13"],
    category: "Design",
  },
  {
    id: "video-6",
    userId: "user-5",
    title: "Best Food Places in LA - Food Tour",
    thumbnail: "/food-tour-restaurants.jpg",
    views: 18920,
    duration: "20:45",
    createdAt: new Date(Date.now() - 518400000).toISOString(),
    likes: ["user-1", "user-4", "user-7"],
    category: "Food & Travel",
  },
]

export const mockGroups: Group[] = [
  {
    id: "group-1",
    name: "Web Developers Community",
    description: "A community for web developers to share knowledge, projects, and opportunities.",
    coverImg: "/web-development-coding.png",
    members: ["user-1", "user-9", "user-10", "user-11", "user-13"],
    privacy: "public",
    category: "Technology",
    admins: ["user-9"],
    createdAt: new Date(Date.now() - 31536000000).toISOString(),
  },
  {
    id: "group-2",
    name: "Photography Enthusiasts",
    description: "Share your best shots, get feedback, and learn from fellow photographers.",
    coverImg: "/photography-camera-lens.jpg",
    members: ["user-1", "user-2", "user-4", "user-11"],
    privacy: "public",
    category: "Art & Photography",
    admins: ["user-4"],
    createdAt: new Date(Date.now() - 26352000000).toISOString(),
  },
  {
    id: "group-3",
    name: "Gaming Squad Pakistan",
    description: "Pakistani gamers unite! Share gameplay, organize tournaments, and make friends.",
    coverImg: "/gaming-esports-controller.jpg",
    members: ["user-1", "user-9", "user-10", "user-12"],
    privacy: "public",
    category: "Gaming",
    admins: ["user-9", "user-10"],
    createdAt: new Date(Date.now() - 15768000000).toISOString(),
  },
  {
    id: "group-4",
    name: "Digital Marketing Experts",
    description: "Learn, share, and grow your digital marketing skills with industry professionals.",
    coverImg: "/digital-marketing-social-media.png",
    members: ["user-1", "user-5", "user-10"],
    privacy: "private",
    category: "Business & Marketing",
    admins: ["user-10"],
    createdAt: new Date(Date.now() - 20736000000).toISOString(),
  },
  {
    id: "group-5",
    name: "UI/UX Designers Hub",
    description: "A creative space for designers to showcase work and discuss design trends.",
    coverImg: "/ui-ux-design-interface.png",
    members: ["user-1", "user-2", "user-11"],
    privacy: "public",
    category: "Design",
    admins: ["user-11"],
    createdAt: new Date(Date.now() - 18144000000).toISOString(),
  },
  {
    id: "group-6",
    name: "Travel & Adventure Club",
    description: "Share travel stories, tips, and plan group adventures around the world.",
    coverImg: "/travel-adventure-mountains.jpg",
    members: ["user-1", "user-2", "user-3", "user-4"],
    privacy: "public",
    category: "Travel",
    admins: ["user-2"],
    createdAt: new Date(Date.now() - 22896000000).toISOString(),
  },
]

export const mockLiveStreams: LiveStream[] = [
  {
    id: "live-1",
    userId: "user-9",
    title: "🔴 LIVE: Playing Fortnite - Join me!",
    thumbnail: "/fortnite-gameplay-live.jpg",
    viewers: 342,
    category: "Gaming",
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    isLive: true,
  },
  {
    id: "live-2",
    userId: "user-10",
    title: "🔴 LIVE: Building a Full-Stack App",
    thumbnail: "/coding-live-programming.jpg",
    viewers: 156,
    category: "Technology",
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    isLive: true,
  },
  {
    id: "live-3",
    userId: "user-2",
    title: "🔴 LIVE: Design Critique Session",
    thumbnail: "/design-critique-workspace.jpg",
    viewers: 89,
    category: "Design",
    startedAt: new Date(Date.now() - 2700000).toISOString(),
    isLive: true,
  },
  {
    id: "live-4",
    userId: "user-11",
    title: "Creating Logo Designs - Q&A",
    thumbnail: "/logo-design-creative.jpg",
    viewers: 0,
    category: "Design",
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    isLive: false,
  },
  {
    id: "live-5",
    userId: "user-4",
    title: "Nature Walk & Photography Tips",
    thumbnail: "/nature-walk-forest-photography.jpg",
    viewers: 0,
    category: "Lifestyle",
    startedAt: new Date(Date.now() - 172800000).toISOString(),
    isLive: false,
  },
]

export const mockGamePosts: GamePost[] = [
  {
    id: "game-1",
    userId: "user-9",
    game: "Call of Duty: Modern Warfare 3",
    caption: "Finally hit Diamond rank! The grind was real 💎🔥",
    image: "/cod-mw3-diamond-rank.jpg",
    achievement: "Diamond Rank",
    score: 4250,
    likes: ["user-1", "user-10", "user-12"],
    comments: [
      {
        id: "game-comment-1",
        userId: "user-10",
        text: "Congrats bro! Let's play together!",
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "game-2",
    userId: "user-12",
    game: "FIFA 24",
    caption: "Packed Messi in my first pack! 🐐⚽",
    image: "/placeholder-fecz0.png",
    likes: ["user-1", "user-9", "user-10"],
    comments: [],
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "game-3",
    userId: "user-10",
    game: "Valorant",
    caption: "ACE! This clutch was insane 🎯",
    image: "/valorant-ace-clutch.jpg",
    achievement: "Ace",
    likes: ["user-1", "user-9", "user-11"],
    comments: [
      {
        id: "game-comment-2",
        userId: "user-9",
        text: "Clean shots bro!",
        createdAt: new Date(Date.now() - 10800000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: "game-4",
    userId: "user-1",
    game: "Elden Ring",
    caption: "Defeated Malenia after 47 attempts! I'm done 😭",
    image: "/elden-ring-boss-victory.jpg",
    achievement: "Boss Defeated",
    likes: ["user-3", "user-9", "user-10"],
    comments: [
      {
        id: "game-comment-3",
        userId: "user-3",
        text: "Respect! That boss is brutal!",
        createdAt: new Date(Date.now() - 18000000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
]

export const mockLikedPages: LikedPage[] = [
  {
    id: "page-1",
    name: "TechCrunch",
    category: "Media & News",
    followers: 8520000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "The latest technology news and information on startups",
  },
  {
    id: "page-2",
    name: "National Geographic",
    category: "Media & News",
    followers: 142000000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "Experience the world through the eyes of National Geographic photographers",
  },
  {
    id: "page-3",
    name: "PlayStation",
    category: "Gaming",
    followers: 38500000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "Official PlayStation page. Play Has No Limits.",
  },
  {
    id: "page-4",
    name: "Adobe Creative Cloud",
    category: "Software",
    followers: 12300000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "Creative apps and services for everyone",
  },
  {
    id: "page-5",
    name: "Nike",
    category: "Sports & Recreation",
    followers: 95000000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "Just Do It. Inspiring athletes everywhere.",
  },
  {
    id: "page-6",
    name: "Gordon Ramsay",
    category: "Chef",
    followers: 18200000,
    coverImg: "/placeholder.svg?height=300&width=800",
    verified: true,
    description: "Official page of Chef Gordon Ramsay",
  },
]
